# -*- coding: utf-8 -*-
"""PRO_C105_soluciónProyecto_1:4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sjAb8GwKoxlRpmuOGsBHqYG1TXwGgTa_

**VERIFICA SI ES UN AÑO BISIESTO**
"""

year=int(input("Ingresa el año para verificar:"))

if(year % 4 == 0 and year % 100 != 0 or year % 400==0):
  print("¡El año es bisiesto!")
else:
  print("El año no es bisiesto")

"""**Lee la altura en centímetros y convierte la altura a pies y pulgadas**"""

cm=int(input("Ingresa la altura en centímetros:"))
inches=0.394*cm
feet=0.0328*cm
print("La longitud en pulgadas",round(inches,2))
print("La longitud en pies",round(feet,2))